// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Alignment {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Alignment {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsAlignment(bb:flatbuffers.ByteBuffer, obj?:Alignment):Alignment {
  return (obj || new Alignment()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsAlignment(bb:flatbuffers.ByteBuffer, obj?:Alignment):Alignment {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Alignment()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

absolute(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

absoluteLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

absoluteArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startAlignment(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addAbsolute(builder:flatbuffers.Builder, absoluteOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, absoluteOffset, 0);
}

static createAbsoluteVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createAbsoluteVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createAbsoluteVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startAbsoluteVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endAlignment(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createAlignment(builder:flatbuffers.Builder, absoluteOffset:flatbuffers.Offset):flatbuffers.Offset {
  Alignment.startAlignment(builder);
  Alignment.addAbsolute(builder, absoluteOffset);
  return Alignment.endAlignment(builder);
}
}
