// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum AxisPartClass {
  NONE = 0,
  WIRE = 1,
  WIRE_SET = 2,
  CIRCLE_CURVE = 3
}
