// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum GeometryClass {
  NONE = 0,
  LINES = 1,
  ELLIPSE_ARC = 2,
  CLOTHOID = 3,
  PARABOLA = 4
}
