// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { GeometryClass } from './geometry-class.js';


export class GeometryRepresentation {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GeometryRepresentation {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

id():number {
  return this.bb!.readUint32(this.bb_pos);
}

mutate_id(value:number):boolean {
  this.bb!.writeUint32(this.bb_pos + 0, value);
  return true;
}

geometryClass():GeometryClass {
  return this.bb!.readInt8(this.bb_pos + 4);
}

mutate_geometry_class(value:GeometryClass):boolean {
  this.bb!.writeInt8(this.bb_pos + 4, value);
  return true;
}

static sizeOf():number {
  return 8;
}

static createGeometryRepresentation(builder:flatbuffers.Builder, id: number, geometry_class: GeometryClass):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.pad(3);
  builder.writeInt8(geometry_class);
  builder.writeInt32(id);
  return builder.offset();
}

}
