// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { Attribute } from './attribute.js';
export { Axis } from './axis.js';
export { AxisPartClass } from './axis-part-class.js';
export { BigShellHole } from './big-shell-hole.js';
export { BigShellProfile } from './big-shell-profile.js';
export { BoundingBox } from './bounding-box.js';
export { CircleCurve } from './circle-curve.js';
export { CircleExtrusion } from './circle-extrusion.js';
export { DoubleVector } from './double-vector.js';
export { FloatVector } from './float-vector.js';
export { Material } from './material.js';
export { Meshes } from './meshes.js';
export { Model } from './model.js';
export { Relation } from './relation.js';
export { RenderedFaces } from './rendered-faces.js';
export { Representation } from './representation.js';
export { RepresentationClass } from './representation-class.js';
export { Sample } from './sample.js';
export { Shell } from './shell.js';
export { ShellHole } from './shell-hole.js';
export { ShellProfile } from './shell-profile.js';
export { ShellType } from './shell-type.js';
export { SpatialStructure } from './spatial-structure.js';
export { Stroke } from './stroke.js';
export { Transform } from './transform.js';
export { Wire } from './wire.js';
export { WireSet } from './wire-set.js';
