// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum RepresentationClass {
  NONE = 0,
  SHELL = 1,
  CIRCLE_EXTRUSION = 2
}
