// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Alignment } from '../../fragments/index/alignment.js';


export class Civil {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Civil {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCivil(bb:flatbuffers.ByteBuffer, obj?:Civil):Civil {
  return (obj || new Civil()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCivil(bb:flatbuffers.ByteBuffer, obj?:Civil):Civil {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Civil()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

alignmentHorizontal(obj?:Alignment):Alignment|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Alignment()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

alignmentVertical(obj?:Alignment):Alignment|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Alignment()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startCivil(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addAlignmentHorizontal(builder:flatbuffers.Builder, alignmentHorizontalOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, alignmentHorizontalOffset, 0);
}

static addAlignmentVertical(builder:flatbuffers.Builder, alignmentVerticalOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, alignmentVerticalOffset, 0);
}

static endCivil(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
